global.Sova = {
  list: require("./list"),
  map: require("./map"),
  condition: require("./condition"),
  plus: require("./plus"),
  minus: require("./minus"),
  multiply: require("./multiply"),
  divide: require("./divide"),
  mod: require("./mod"),
  and: require("./and"),
  or: require("./or"),
  not: require("./not"),
  greater: require("./greater"),
  greaterOrEquals: require("./greaterOrEquals"),
  less: require("./less"),
  lessOrEquals: require("./lessOrEquals"),
  equals: require("./equals"),
  accuratlyEquals: require("./accuratlyEquals"),
  notEquals: require("./notEquals"),
  notAccuratlyEquals: require("./notAccuratlyEquals"),
  multiline: require("./multiline")
};
