#!/bin/sh

# script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

input_directory=$1
output_directory=$2

# Clean output directory
rm -rf $output_directory

# Copy all non-sova files
rsync -a --exclude '*.sv' $input_directory/* $output_directory

# # Compile all sova files
for sova_file in $(find $input_directory -type f -name "*.sv")
do
	relative_sova_file_path=${sova_file#$input_directory}
	js_file="$output_directory/${relative_sova_file_path%.*}.js"
	cat $sova_file | $DIR/compile/compile.js >> $js_file
done
