#!/bin/sh

# script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

input_directory=$1
output_directory=$2

# Clean output directory
rm -rf $output_directory

# Copy all non-sova files
rsync -a --exclude '*.sv' $input_directory/* $output_directory

# Compile all sova files
for sova_file in $(find $input_directory -type f -name "*.sv")
do
	cat $sova_file | $DIR/compile/compile.js >> './output/index.js'
done

node './output/index.js'
